#!/usr/bin/python

import openshift.wsgi
# # reuse the application callable from openshift.wsgi
application = openshift.wsgi.application

# from pimarket import pimarket.wsgi
# reuse the application callable from openshift.wsgi
# application = pimarket.wsgi.application
